config/routes.rb
Rails.application.routes.draw do
  resources :measures

end

app/models/measure.rb
class Measure < ActiveRecord::Base
  serialize :info, :set
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController
  skip_before_filter :verify_authenticity_token

  before_action :set_measure, only: [:show, :edit, :update, :destroy]

  # GET /measures
  # GET /measures.json
  def index
    @measures = Measure.all
  end

  # GET /measures/1
  # GET /measures/1.json
  def show
  end

  # GET /measures/new
  def new
    @measure = Measure.new
  end

  # GET /measures/1/edit
  def edit
  end

  # POST /measures
  # POST /measures.json
  def create
    @measure = Measure.new
    set_measure_params
    respond_to do |format|
      if @measure.save
        format.html { redirect_to @measure, notice: 'Measure was successfully created.' }
        format.json { render :show, status: :created, location: @measure }
      else
        format.html { render :new }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measures/1
  # PATCH/PUT /measures/1.json
  def update
    respond_to do |format|
      set_measure_params
      if @measure.save
        format.html { redirect_to @measure, notice: 'Measure was successfully updated.' }
        format.json { render :show, status: :ok, location: @measure }
      else
        format.html { render :edit }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measures/1
  # DELETE /measures/1.json
  def destroy
    @measure.destroy
    respond_to do |format|
      format.html { redirect_to measures_url, notice: 'Measure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measure
      @measure = Measure.find(params[:id])
      @images = @measure.from.delete "images" 
      @front = @measure.set["front"]
      @side = @measure.set["side"]
    end
    def set_measure_params
      @measure.from = params.require("measure").fetch("from")
      @measure.set = params.require("measure").fetch("set")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/measures_helper.rb
module MeasuresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AspectServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/measures/_form.html.erb
<%= form_for(@measure) do |f| %>
  <% if @measure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measure.errors.count, "error") %> prohibited this measure from being saved:</h2>

      <ul>
      <% @measure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br>
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :set %><br>
    <%= f.text_field :set %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/measures/edit.html.erb
<h1>Editing Measure</h1>

<%= render 'form' %>

<%= link_to 'Show', @measure %> |
<%= link_to 'Back', measures_path %>

app/views/measures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Measures</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>Set</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @measures.each do |measure| %>
      <tr>
        <td><%= measure.from %></td>
        <td><%= measure.set %></td>
        <td><%= link_to 'Show', measure %></td>
        <td><%= link_to 'Edit', edit_measure_path(measure) %></td>
        <td><%= link_to 'Destroy', measure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Measure', new_measure_path %>

app/views/measures/new.html.erb
<h1>New Measure</h1>

<%= render 'form' %>

<%= link_to 'Back', measures_path %>

app/views/measures/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Medidas de <%= @measure.from["email"] %></h1>

<div class="content">
  <table>
    <thead>
      <tr>
        <td>Medida</td>
        <td><strong>Frente</strong></td>
        <td><strong>Lado</strong></td>
      </tr>
    </thead>
    <tbody>
      <% @front.each do |measure, value_front| %>
          <tr>
            <td> <strong><%= measure %></strong></td>
            <td> <%= value_front %></td>
            <td> <%= @side[measure] %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>
<hr />
<h1>Images</h1>
<% @images.each do |image| %>
  <%= image_tag image %>
<% end %>
<hr />

<%= link_to 'Edit', edit_measure_path(@measure) %> |
<%= link_to 'Back', measures_path %>